import { DetailGroup, Disclosure } from './details';
import { Economics, BudgetSelection } from './economics';
export function UsePlan(){return <>
  <header className="selected-phase-intro"><span className="eyebrow">PHASE 2 / AFTER ASSESSING THE GUIDANCE</span><h2>Test the guidance in use</h2><p>A sound guide may still be unhelpful during a real change. This phase asks whether an agent does better when it receives the guide.</p></header>
  <section className="phase-procedure"><h3>What we start with</h3><p>Use the guide produced by the verifier for each preparation attempt in the comparison. It contains only claims the verifier accepted. If no claims were accepted, use the empty guide and keep its preparation cost.</p><p>We do not select only guides that scored well in the independent assessment. Keeping poor outcomes lets us test the reliability of the whole preparation method.</p><p>The tasks come from the same project’s history. Choose them before preparing their guide, check that its sources match their code versions, and establish how to assess each result. Keep the tasks and historical solutions hidden from the drafter and verifier.</p>
  <h3>What the agents do</h3><p>Ask two groups to make the same changes. <strong>Sources only</strong> receives the permitted project files. <strong>Sources and prepared guidance</strong> receives those files and the fixed guide.</p><p>Both groups plan, implement and review their work. Both receive the same rules for review checkpoints and corrections, including another check when their plan changes. This phase does not add the interactive layer.</p>
  <h3>How we assess the result</h3><p>An independent assessment checks whether each change fulfils its task and respects the applicable project rules. The historical implementation is assessed too; it may contain a mistake, so copying it is not automatically success.</p><p>Compare quality, failures and total cost. Preparation counts as part of the guidance method’s cost. All attempts remain in the record, including unfinished work and exhausted budgets.</p>
  <h3>What this phase produces</h3><p>A comparison showing where the guide helped, where it did not and what using it cost. That gives us a basis for deciding whether to test interaction, repair the method or stop.</p></section>
  <DetailGroup><Disclosure id="use-fairness" title="How do we keep the comparison fair?"><p>Use matched tasks, code versions, coding models, source access and ordinary review settings. Give each method the same total allowance. Preparing the guide uses part of the guidance method’s allowance.</p><p>Before preparing a guide, record which tasks will use it and check that it applies to their code versions. Share the preparation cost across those tasks. If a task fails, keep its share of the cost in the results.</p><p>If hidden assessment feedback helped repair a guide, record that history. The repaired material can help develop the method, but cannot also provide independent evidence that the original method worked.</p><p>The code execution environment and its access boundaries must be tested before use. Before the assessor scores the experiment, test it on other cases with well supported expected answers. Check whether it recognises both valid solutions and plausible mistakes.</p></Disclosure>
  <Disclosure id="use-costs" title="Read how costs and reuse will be compared"><Economics/></Disclosure>
  <Disclosure id="use-budget" title="Read how the spending allowance will be chosen"><BudgetSelection/></Disclosure></DetailGroup>
  <p className="phase-handoff">The next phase asks a different question: once the agent has a guide, does consultation and checking during work add anything further?</p>
</>}
export function InteractionPlan(){return <>
  <header className="selected-phase-intro"><span className="eyebrow">PHASE 3 / AFTER TESTING THE GUIDE IN USE</span><h2>Test interaction during work</h2><p>This phase tests the part of the layer that helps an agent apply the guidance while a change is taking shape.</p></header>
  <section className="phase-procedure"><h3>What we start with</h3><p>Use the established guidance and coding comparison, then add a checker. The checker is the role that asks whether a proposed action respects the rules and whether an exception is justified.</p><h3>What the agents do</h3><p>Run all three groups together: <strong>Sources only</strong>; <strong>Sources and prepared guidance</strong>; and <strong>Sources, prepared guidance and interaction</strong>.</p><p>The third group can consult the layer about its approach. At required checkpoints, the checker can ask the agent to explain its choices. It can require a correction or stop work when a necessary decision remains unresolved.</p><p>All groups still receive ordinary reviews under matched rules. The interactive group does not simply receive an extra review or a larger budget.</p><h3>How we assess the result</h3><p>Assess the resulting code independently, as in Phase 2. Also examine the checker’s interventions: did they catch a real problem, miss one or unnecessarily obstruct valid work?</p><p>Run the first two groups again alongside the interactive group. If we used their old Phase 2 scores, a change in the model or procedure could be mistaken for a benefit of interaction.</p><h3>What this phase produces</h3><p>A report on the additional benefit, failures and cost of interaction. Together, the three phases tell us whether the layer can construct defensible guidance, whether that guidance helps and whether checking its use adds further value.</p></section>
  <DetailGroup><Disclosure id="interaction-checks" title="What happens when the agent changes its plan?"><p>The agent must submit an updated plan when a change affects the decisions it relies on. Defined checkpoints and detected changes trigger review, and required checks pause further work until a decision is recorded.</p><p>All groups have the same review trigger policy and correction limits. The interactive group adds questions grounded in the guide. We must test the actual detection and pause controls; this is not a claim of continuous monitoring of every action.</p></Disclosure><Disclosure id="interaction-assessment" title="How will the checker itself be assessed?"><p>Before using them in the experiment, test the checker and the separate agent that assesses its decisions. Use other cases where the evidence supports the expected answer. Include real violations, legitimate exceptions, unnecessary objections and cases where the available evidence cannot settle the question.</p><p>Retain questions, answers, revisions, stops and costs. The checker cannot judge its own success, and hidden assessment feedback does not return to working agents.</p></Disclosure></DetailGroup>
  <p className="phase-handoff">The first trial ends with its evidence and limitations. Confirmation on fresh cases would be a separate decision, not an automatic claim that the layer works everywhere.</p>
</>}
