'use client';
import { sitePath } from './site-path';

import { useMemo, useState, type ReactNode } from 'react';
import { ArrowUpRight, Search, ArrowRight, Download, FileText, ChevronLeft, ChevronRight } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Pagination, PaginationContent, PaginationItem } from '@/components/ui/pagination';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import evidence from './evidence.json';

export const repoNames:Record<string,string>={netbox:'NetBox',wagtail:'Wagtail','paperless-ngx':'Paperless-ngx',httpx:'HTTPX'};
const statusNames:Record<string,string>={advance:'Candidate for pilot',control:'Control case',defer:'Deferred',calibration:'Calibration',merge:'Merged',reject:'Rejected'};
export function Disclosure({id,title,summary,children}:{id:string,title:string,summary?:string,children:ReactNode}){return <AccordionItem value={id} className="disclosure"><AccordionTrigger className="disclosure-trigger"><span><strong>{title}</strong>{summary&&<span className="disclosure-summary">{summary}</span>}</span></AccordionTrigger><AccordionContent className="disclosure-body">{children}</AccordionContent></AccordionItem>}
export function DetailGroup({children}:{children:ReactNode}){return <Accordion className="detail-group">{children}</Accordion>}
export function RepositoryCards({showCounts=false}:{showCounts?:boolean}){const descriptions:Record<string,string>={netbox:'Infrastructure conventions, permissions and background jobs.',wagtail:'Publishing, revisions, content representations and scoped access.','paperless-ngx':'Document pipelines, ownership, workflow actions and parser boundaries.',httpx:'Request lifecycles, streaming, authentication and transports.'};return <div className="repo-grid">{evidence.repositories.map(repo=><a href={repo.url} key={repo.id} className="repo-card" target="_blank" rel="noreferrer"><div className="repo-title"><h3>{repoNames[repo.id]}</h3><ArrowUpRight size={17}/></div><p>{descriptions[repo.id]}</p>{showCounts?<span className="repo-meta">{repo.advance} candidates to develop · {repo.controls} controls</span>:<span className="repo-meta">Explore the pinned source</span>}</a>)}</div>}

export function Examples(){return <Tabs defaultValue="timing" className="examples"><p className="example-picker-label">These are simplified illustrations of guidance the layer might provide. They are not actual outputs from the layer or the final instructions that will be sent to an agent. Select an example to read it.</p><TabsList className="example-tabs" aria-label="Choose an example"><TabsTrigger value="timing">1. Keeping an accurate change history</TabsTrigger><TabsTrigger value="conflict">2. Resolving conflicting documentation</TabsTrigger><TabsTrigger value="authority">3. Knowing when the evidence is insufficient</TabsTrigger></TabsList>
<TabsContent value="timing"><ExampleBody label="EXAMPLE 1 / NETBOX" title="The name changes correctly, but the history can still be wrong." observation="Imagine renaming a device from router-01 to router-02. Before the code changes the name, it must preserve the original record so the history can show router-01 as the old value. NetBox’s standard editing process already does this. Code that edits an object directly may need to do it explicitly. Saving a copy after the rename is too late: that copy would already say router-02." rule="First check how this edit is being made. If it uses NetBox’s standard editing process, use the existing history handling. If the code edits the object directly, preserve its original state before changing the name. Don’t add a second copy where the framework already takes one." meaning="We would test both situations. The agent should add the missing step for a direct edit, but avoid adding unnecessary work to the standard process. This would show whether the guidance helps it apply a rule correctly, including the exception." caseId="N12"/></TabsContent>
<TabsContent value="conflict"><ExampleBody label="HTTPX / COOKIE HANDLING" title="The guide discourages something the code still allows." observation="HTTPX is a library for making web requests. Its guide says that a client does not support setting cookies separately on each request. The code we inspected still accepts those cookies, while warning that this use is being phased out." rule="Set cookies on the client, as the guide recommends. If describing the current behaviour, explain that request-level cookies are still accepted with a warning; they are not blocked by the code." meaning="We would look for an answer that notices the disagreement and explains it. Copying the guide without checking the implementation would produce a misleading rule." caseId="H11"/></TabsContent>
<TabsContent value="authority"><ExampleBody label="WAGTAIL / INTERNAL PERMISSION APIS" title="A long-lived extension would depend on internal permission code." observation="Wagtail is a content-management system that developers can extend. In this example, an agent proposes building an extension around Wagtail’s internal permission-policy registry: the machinery that looks up who may act on a record. The extension is expected to keep working through upgrades. That makes this dependency worth checking. Wagtail’s documentation explicitly says these internal APIs are outside its normal policy for handling incompatible changes. It makes a narrow exception for a documented registration function." rule="The proposed extension would depend on internal permission APIs that are not covered by Wagtail’s normal compatibility policy. Don’t promise that this dependency will remain compatible through upgrades. For the documented task of registering a model, use register_permission_policy(MyModel); that exception does not make the other permission APIs, or every use of the function, supported." meaning="The trigger is the proposed dependence on internal permission machinery, rather than an ordinary function call. The layer should identify that boundary and reuse the guidance wherever it applies. This illustrative answer assumes the documentation is visible. With code alone, we would instead expect the layer to say that the support commitment cannot be established. The test should penalise both an invented guarantee and a blanket rejection of the documented exception." caseId="W18"/></TabsContent>
<p className="caption">Before an experiment runs, the agent’s instructions will need the relevant APIs, precise requirements, exceptions and references to the evidence it is allowed to see.</p></Tabs>}
function ExampleBody({label,title,observation,rule,meaning,caseId}:{label:string,title:string,observation:string,rule:string,meaning:string,caseId:string}){const item=evidence.cases.find(c=>c.id===caseId)!;return <div className="example-body"><div><span className="eyebrow">{label}</span><h3>{title}</h3><p>{observation}</p><a className="text-link" href={item.reference.url} target="_blank" rel="noreferrer">Read the project’s published guidance <ArrowUpRight size={15}/></a></div><div className="example-answer"><span className="eyebrow">ILLUSTRATIVE GUIDANCE</span><blockquote>{rule}</blockquote><p>{meaning}</p></div></div>}

const repoItems=[{value:'all',label:'All repositories'},...Object.entries(repoNames).map(([value,label])=>({value,label}))];
const statusItems=[{value:'all',label:'All screening decisions'},...Object.entries(statusNames).map(([value,label])=>({value,label}))];
export function EvidenceExplorer(){
const [query,setQuery]=useState(''),[repo,setRepo]=useState('all'),[status,setStatus]=useState('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<(typeof evidence.cases)[number]|null>(null);
const filtered=useMemo(()=>evidence.cases.filter(c=>(repo==='all'||c.repo===repo)&&(status==='all'||c.status===status)&&`${c.id} ${c.title} ${c.claim} ${c.family}`.toLowerCase().includes(query.toLowerCase())),[query,repo,status]);
const pageCount=Math.max(1,Math.ceil(filtered.length/8));const current=Math.min(page,pageCount-1);const visible=filtered.slice(current*8,current*8+8);
return <div className="evidence-explorer" id="case-library"><div className="library-intro"><p>Each record links to a published reference and explains how we might test the decision. Candidates for the pilot still need a working task and a reliable way to score it.</p><a className="text-link" href={sitePath("/evidence/cross-repository-decision-inventory.csv")} download><Download size={16}/>Download inventory</a></div><div className="library-filters"><div className="search-field"><Search size={17}/><Input aria-label="Search cases" placeholder="Search a decision, topic or case ID…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></div><Select items={repoItems} value={repo} onValueChange={v=>{setRepo(v||'all');setPage(0)}}><SelectTrigger className="filter-select" aria-label="Filter by repository"><SelectValue/></SelectTrigger><SelectContent>{repoItems.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select><Select items={statusItems} value={status} onValueChange={v=>{setStatus(v||'all');setPage(0)}}><SelectTrigger className="filter-select" aria-label="Filter by screening decision"><SelectValue/></SelectTrigger><SelectContent>{statusItems.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></div><output className="result-count">{filtered.length} of {evidence.cases.length} records</output>
<Sheet><div className="case-table"><Table><TableHeader><TableRow><TableHead>Case / decision</TableHead><TableHead>Repository</TableHead><TableHead>Screening decision</TableHead></TableRow></TableHeader><TableBody>{visible.map(c=><TableRow key={c.id}><TableCell><SheetTrigger className="case-trigger" onClick={()=>setSelected(c)}><span className="case-id">{c.id}</span><span>{c.title}</span><ArrowRight size={15}/></SheetTrigger></TableCell><TableCell>{repoNames[c.repo]}</TableCell><TableCell><span className={`pill ${c.status==='advance'?'blue':c.status==='control'?'amber':'neutral'}`}>{statusNames[c.status]}</span></TableCell></TableRow>)}</TableBody></Table></div>
{filtered.length===0&&<Empty><EmptyHeader><EmptyTitle>No matching cases</EmptyTitle><EmptyDescription>Try a broader phrase or clear the filters.</EmptyDescription></EmptyHeader><Button variant="outline" onClick={()=>{setQuery('');setRepo('all');setStatus('all');setPage(0)}}>Clear filters</Button></Empty>}
<SheetContent className="case-sheet"><SheetHeader><span className="eyebrow">{selected?.id} / {selected&&repoNames[selected.repo]}</span><SheetTitle className="case-sheet-title">{selected?.title||'Case details'}</SheetTitle><SheetDescription>Candidate case · {selected&&statusNames[selected.status]}</SheetDescription></SheetHeader>{selected&&<div className="case-sheet-body"><CaseSection title="The rule this case could test">{selected.claim}</CaseSection><CaseSection title="Proposed test">{selected.challenge}</CaseSection><CaseSection title="Why it was classified this way">{selected.reason}</CaseSection><CaseSection title="What remains">We still need to build the task, check that the scoring works and verify that the allowed inputs don’t give away the answer. No blinded run has been recorded for this case.</CaseSection><div className="case-section"><h3>Source evidence</h3><a className="source-link" href={selected.reference.url} target="_blank" rel="noreferrer">Read the project’s published guidance <ArrowUpRight size={15}/></a>{selected.code.map((c,i)=><a className="code-link" key={`${c.url}-${i}`} href={c.url} target="_blank" rel="noreferrer">{c.path}:{c.line}<ArrowUpRight size={14}/></a>)}</div><p className="caption">{selected.previous?'This was part of the original twelve-case development audit.':'Added to the evidence review on 5 September 2026.'} Other cases may test the same underlying decision. We will account for that relationship when interpreting the results.</p></div>}</SheetContent></Sheet>
{filtered.length>0&&<Pagination className="library-pagination" aria-label="Case pages"><PaginationContent><PaginationItem><Button variant="outline" size="sm" disabled={current===0} aria-label="Previous case page" onClick={()=>setPage(current-1)}><ChevronLeft size={16}/>Previous</Button></PaginationItem><PaginationItem><span className="page-count">{current+1} / {pageCount}</span></PaginationItem><PaginationItem><Button variant="outline" size="sm" disabled={current===pageCount-1} aria-label="Next case page" onClick={()=>setPage(current+1)}>Next<ChevronRight size={16}/></Button></PaginationItem></PaginationContent></Pagination>}
</div>}
function CaseSection({title,children}:{title:string,children:ReactNode}){return <div className="case-section"><h3>{title}</h3><p>{children}</p></div>}
export function EvidenceDownloads(){return <div className="download-list">{[['working-poc-plan.md','Working experiment plan','Current pilot design, proposals and open decisions'],['plan-changes.md','Plan change record','What changed and how it affects the experiment'],['cross-repository-inventory-review.md','Repository assessment','Findings, limitations and the next gate'],['cross-repository-inventory-cards.md','All 84 case cards','References, interpretations and challenges'],['inventory-screening-protocol.md','Screening protocol','How candidates were included or excluded'],['case-inventory.json','Structured evidence','Case records and pinned source links']].map(([file,title,sub])=><a key={file} href={sitePath(`/evidence/${file}`)} download><FileText size={20}/><span><strong>{title}</strong><small>{sub}</small></span><Download size={17}/></a>)}</div>}
