import { PageLink } from './page-link';
import { DetailGroup, Disclosure, Examples } from './details';
import { FamiliarityChecks } from './familiarity-checks';
export function GuidancePlan(){return <>
<header className="selected-phase-intro"><span className="eyebrow">PHASE 1 / OUR CURRENT FOCUS</span><h2>Reconstruct guidance</h2><p>We begin with project evidence and end with an assessed guide. This phase tests whether the rules are defensible before we ask an agent to use them.</p></header>
  <section className="section-block" id="guidance-method"><div className="section-heading"><span className="section-no">01</span><div><span className="eyebrow">THE WORK IN THIS PHASE</span><h2>From project evidence to an assessed guide</h2></div></div>
    <ol className="method-steps">
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">1</span><h3>Choose the evidence and establish what it supports</h3></div><div className="method-step-content"><p>Select one repository and a few different kinds of decisions. For each, establish the applicable rule, exceptions and any uncertainty using project records and reproducible behaviour.</p><p>Prepare separate files for the layer and for assessment. The layer receives only its permitted project evidence. The assessment record stays hidden.</p><DetailGroup><Disclosure id="source-access" title="What can the layer read?"><p>Use a fixed code version and the project instructions that actually applied to it. Record every supplied file and the reason it belongs in the input. Do not select files to hint at a hidden answer.</p><p>Some cases will expose a rule in documentation; others may require interpreting code. Record that distinction for each claim. Never remove applicable project instructions to manufacture an inference test.</p><p>If the evidence cannot establish a central requirement, leave that case out of scored assessment. Record it as unresolved.</p></Disclosure></DetailGroup></div></li>
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">2</span><h3>Ask the drafter to prepare guidance</h3></div><div className="method-step-content"><p>The drafter is the part of the interpretation layer that proposes rules. It explains what each rule means, where it applies, what supports it and where an exception or uncertainty remains.</p><p>It does not receive a later coding task or the assessment answers. We keep its original draft so that mistakes remain visible even if they are corrected later.</p></div></li>
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">3</span><h3>Check the draft against its evidence</h3></div><div className="method-step-content"><p>A separate verifier checks the drafter’s claims. It can accept a supported claim, request a correction or leave it unresolved. Any permitted revisions follow limits fixed before the run.</p><p>Save both the draft and the accepted guide, together with the verifier’s decisions. Acceptance means that the verifier found evidence support. It is not approval from a project owner.</p></div></li>
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">4</span><h3>Assess the guidance independently</h3></div><div className="method-step-content"><p>A separate assessment uses the hidden reference evidence to examine the draft, the accepted guide and the verifier’s decisions. The verifier cannot judge its own success.</p><p>Check what the guide got right, what it missed and what it asserted without support. Also check whether the verifier accepted a bad claim or rejected a valid one. Record preparation time, cost and failed attempts.</p><DetailGroup><Disclosure id="guidance-assessment" title="How will we know that the assessment is reliable?"><p>Build examples containing supported rules, plausible mistakes, legitimate alternatives and statements the evidence cannot settle. Explain the expected assessment from the sources and behaviour, rather than taking another model’s agreement as proof.</p><p>Test any model used to verify or assess guidance on separate examples before using its scores. Fix the criteria, error limits and required coverage in advance. Examples used to repair the assessment remain development material.</p><p>Assess coverage as well as accuracy. An empty guide should not pass simply because it contains no incorrect claims. Conflicts and valid exceptions matter alongside the usual rule.</p></Disclosure></DetailGroup></div></li>
    </ol>
  </section>
  <section className="phase-scope" id="phase-deliverable"><div><span className="eyebrow">WHAT WE WILL HAVE</span><h2>A result we can examine before building more.</h2><p>A versioned guide, its claim evidence, the original draft, the verifier’s decisions and an independent assessment. The report includes omissions, failures, uncertainty and preparation costs.</p></div><div><h3>The decision at the end</h3><p>Decide whether the guide is defensible enough to test in a coding task, whether preparation needs repair or whether to stop. A positive result is not required to finish this phase.</p><p>This phase can establish the quality of the guidance in the tested cases. It cannot show that the guidance improves code or pays for itself.</p></div></section>
  <section className="section-block" id="phase-controls"><div className="section-heading"><span className="section-no">02</span><div><span className="eyebrow">KEEPING THE TEST CREDIBLE</span><h2>Build the controls this phase actually uses</h2></div></div><p className="section-intro">The drafter, verifier and independent assessor need separate contexts and explicit access boundaries. We must record what each received and prevent hidden assessment material from reaching the working roles.</p><DetailGroup>
    <Disclosure id="phase-technology" title="What needs to be built now, and what can wait?"><p>Now we need permitted input packs, isolated role calls, bounded outputs, records of decisions and costs, and protected assessment material. Any tool exposed to a role must pass the relevant boundary tests before use.</p><p>Start with controlled reading of supplied files. Coding agents, automated code review and the interactive checker belong to later phases. We do not need to implement them to assess a guide.</p><p>If an agent is allowed to execute code to inspect a source, that capability needs the full execution restrictions and testing before it is enabled. Deferring coding tasks does not waive containment for tools we actually expose.</p><p><PageLink className="text-link" href="/#technical-setup">Read the proposed setup for the complete trial.</PageLink></p></Disclosure>
    <Disclosure id="familiarity" title="Could the model already know the public project?"><p>Yes. Separate probes will look for signs of familiarity during repository and case selection. They cannot prove that the model has never seen the code. Results must distinguish evidence supplied in the run from possible prior knowledge.</p><FamiliarityChecks/></Disclosure>
    <Disclosure id="phase-budget" title="How will we limit the work and cost?"><p>Before model calls, agree a spending ceiling and limits for drafting, verification, revisions and assessment. Use separate development material for any authorised calibration. Fix the scored run settings before opening its results.</p><p>Keep failed preparation and exhausted attempts in the report. The matched budgets for coding comparisons apply in Phases 2 and 3. Phase 1 records preparation costs but cannot calculate savings from code changes it has not tested.</p></Disclosure>
    <Disclosure id="phase-one-production" title="How does this differ from production?"><p>Production would ask a responsible owner to approve or revise the proposed rules. No project owner is available for this POC. We can test whether claims are supported by public evidence, but cannot certify an owner’s unrecorded intentions.</p><p>Production would also keep guidance current and serve it during work. This phase assesses a fixed version. Later phases test its use; maintenance remains a possible separate study.</p></Disclosure>
    <Disclosure id="phase-one-examples" title="See illustrative examples of the guidance"><p>NetBox is a public application for documenting network infrastructure. The examples below illustrate guidance about its change history and other project rules. They are shortened explanations, not the exact instructions or selected cases for this phase.</p><Examples/></Disclosure>
  </DetailGroup></section>
</>}
