import { PageLink } from './page-link';
import { DetailGroup, Disclosure, Examples } from './details';
import { FamiliarityChecks } from './familiarity-checks';
export function GuidancePlan(){return <>
<header className="selected-phase-intro"><span className="eyebrow">PHASE 1 / OUR CURRENT FOCUS</span><h2>Reconstruct guidance</h2><p>This is where we start. We will choose the evidence, ask the layer to prepare guidance and check what it got right or wrong.</p></header>
  <section className="section-block" id="guidance-method"><div className="section-heading"><span className="section-no">01</span><div><span className="eyebrow">THE WORK IN THIS PHASE</span><h2>From project evidence to an assessed guide</h2></div></div>
    <ol className="method-steps">
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">1</span><h3>Choose the evidence and establish what it supports</h3></div><div className="method-step-content"><p>Choose one project and a small set of rules to investigate. Establish what the project’s records and code tell us about each rule. Record exceptions and anything we cannot settle.</p><p>Prepare separate files for the layer and for assessment. The drafter and verifier receive the project files chosen for the test. They cannot read the separate record used to assess their answers.</p><DetailGroup><Disclosure id="source-access" title="What can the layer read?"><p>Use a fixed code version and the project instructions that actually applied to it. Record every supplied file and the reason it belongs in the input. Do not select files to hint at a hidden answer.</p><p>Some cases will expose a rule in documentation; others may require interpreting code. Record that distinction for each claim. Never remove applicable project instructions to manufacture an inference test.</p><p>If the evidence cannot establish a central requirement, leave that case out of scored assessment. Record it as unresolved.</p></Disclosure></DetailGroup></div></li>
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">2</span><h3>Ask the drafter to prepare guidance</h3></div><div className="method-step-content"><p>The drafter is the part of the interpretation layer that proposes rules. It explains what each rule means, where it applies, what supports it and where an exception or uncertainty remains.</p><p>It does not receive a later coding task or the assessment answers. We keep its original draft so that mistakes remain visible even if they are corrected later.</p></div></li>
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">3</span><h3>Check the draft against its evidence</h3></div><div className="method-step-content"><p>A separate verifier checks the drafter’s claims. It can accept a supported claim, request a correction or leave it unresolved. We decide in advance how many corrections it can request and how much preparation can cost.</p><p>Save both the draft and the accepted guide, together with the verifier’s decisions. Acceptance means that the verifier found evidence support. It is not approval from a project owner.</p></div></li>
      <li className="method-step"><div className="method-step-heading"><span className="method-step-number">4</span><h3>Assess the guidance independently</h3></div><div className="method-step-content"><p>A separate assessment uses the hidden reference evidence to examine the draft, the accepted guide and the verifier’s decisions. The verifier cannot judge its own success.</p><p>Check what the guide got right, what it missed and what it asserted without support. Also check whether the verifier accepted a bad claim or rejected a valid one. Record preparation time, cost and failed attempts.</p><DetailGroup><Disclosure id="guidance-assessment" title="How will we know that the assessment is reliable?"><p>Build examples containing supported rules, plausible mistakes, legitimate alternatives and statements the evidence cannot settle. Explain the expected assessment from the sources and behaviour, rather than taking another model’s agreement as proof.</p><p>Test any model used to verify or assess guidance on separate examples before using its scores. Fix the criteria, error limits and required coverage in advance. Examples used to repair the assessment remain development material.</p><p>For each case, write down which rules the evidence supports, which alternative answers are valid and what counts as a serious mistake. Check for missing rules as well as incorrect ones. An empty guide has no false claims, but it has not recovered any rules either.</p><p>We can measure coverage of the decisions we examined. We cannot claim to have checked every important rule in the project. These case records and pass criteria still need to be completed.</p></Disclosure></DetailGroup></div></li>
    </ol>
  </section>
  <section className="phase-scope" id="phase-deliverable"><div><span className="eyebrow">WHAT WE WILL HAVE</span><h2>A result we can examine before building more.</h2><p>We will save the guide and its original draft, with the evidence for each claim. The report will explain the verifier’s decisions, the mistakes and omissions found by independent assessment, and what preparation cost.</p></div><div><h3>The decision at the end</h3><p>Decide whether to continue to coding tasks, improve the preparation method or stop. A poor result can justify stopping the study.</p><p>If we continue, we will not select only the guides that scored well. Each preparation attempt in the comparison keeps its result and cost, including an empty guide. A repaired method needs a separately recorded version and fresh preparation where required.</p><p>This phase can establish the quality of the guidance in the tested cases. It cannot show that the guidance improves code or pays for itself.</p></div></section>
  <section className="section-block" id="phase-controls"><div className="section-heading"><span className="section-no">02</span><div><span className="eyebrow">KEEPING THE TEST CREDIBLE</span><h2>Build the controls this phase actually uses</h2></div></div><p className="section-intro">Each agent starts in a separate conversation and receives only the files assigned to it. The system must prevent the drafter and verifier from opening the assessment answers. We also record exactly what each agent received.</p><DetailGroup>
    <Disclosure id="phase-technology" title="What needs to be built now, and what can wait?"><p>First, build a way to give each agent its assigned files, limit its work and save its decisions and costs. Keep the assessment answers separate and inaccessible. Any tool exposed to a role must pass the relevant boundary tests before use.</p><p>Start with controlled reading of supplied files. Coding agents, automated code review and the interactive checker belong to later phases. We do not need to implement them to assess a guide.</p><p>If an agent is allowed to execute code to inspect a source, that capability needs the full execution restrictions and testing before it is enabled. Deferring coding tasks does not waive containment for tools we actually expose.</p><p><PageLink className="text-link" href="/#technical-setup">Read the proposed setup for the complete trial.</PageLink></p></Disclosure>
    <Disclosure id="guidance-task-selection" title="When do we choose the later coding tasks?"><p>If a guide will be used in Phase 2, choose its intended tasks before preparing it. Check that the guide’s sources belong to the code versions those tasks use. A guide based on a later version could reveal information that was unavailable at the time.</p><p>The investigator selects the tasks. The drafter and verifier do not see them or their solutions. We must not look at a finished guide and then choose only changes it happens to help.</p></Disclosure>
    <Disclosure id="familiarity" title="Could the model already know the public project?"><p>Yes. A model may recognise public code from before our study. The checks below look for signs of that knowledge. They cannot prove that the code was unfamiliar.</p><FamiliarityChecks/></Disclosure>
    <Disclosure id="phase-budget" title="How will we limit the work and cost?"><p>Before model calls, agree a spending ceiling and limits for drafting, verification, revisions and assessment. Use separate development material for any authorised calibration. Fix the scored run settings before opening its results.</p><p>Keep failed preparation and exhausted attempts in the report. The matched budgets for coding comparisons apply in Phases 2 and 3. Phase 1 records preparation costs but cannot calculate savings from code changes it has not tested.</p></Disclosure>
    <Disclosure id="phase-one-production" title="How does this differ from production?"><p>Production would ask a responsible owner to approve or revise the proposed rules. No project owner is available for this POC. We can test whether claims are supported by public evidence, but cannot certify an owner’s unrecorded intentions.</p><p>Production would also keep guidance current and serve it during work. This phase assesses a fixed version. Later phases test its use; maintenance remains a possible separate study.</p></Disclosure>
    <Disclosure id="phase-one-examples" title="See illustrative examples of the guidance"><p>NetBox is a public application for documenting network infrastructure. The examples below illustrate guidance about its change history and other project rules. They are shortened explanations, not the exact instructions or selected cases for this phase.</p><Examples/></Disclosure>
  </DetailGroup></section>
</>}
