import type { Metadata } from 'next';
import { Shell, chapterUrl } from './ui';
import { PhasePlans } from './phase-plans';
import { GuidancePlan } from './guidance-plan';
import { UsePlan, InteractionPlan } from './coding-plans';
import { FullMethod } from './full-method';
export const dynamic = 'force-static';
export const metadata:Metadata={title:'The plan | Interpretation layer trial',description:'Why we are testing the interpretation layer, how the three phases fit together, and the plan for each phase.'};
export default function Plan(){return <Shell active="experiment">
  <header className="plan-opening"><span className="eyebrow">AI ENGINEERING PLAYBOOK / THE FIRST TRIAL</span><h1>Does understanding the project’s rules help an agent make better changes?</h1><p className="lead">An AI agent can read code and follow instructions. The playbook proposes an interpretation layer that turns evidence about a project into guidance, then helps the agent apply it during work. This POC tests whether those added steps are useful.</p><p>The proposal comes from <a className="text-link" href={chapterUrl} target="_blank" rel="noreferrer">Chapter 4 of the AI Engineering Playbook</a>. We will start with one public project and a small set of different decisions, so we can inspect the results before building a wider study.</p></header>
  <section className="connected-story" id="how-phases-fit" aria-labelledby="how-phases-fit-title"><span className="eyebrow">ONE EXPERIMENT, BUILT IN STAGES</span><h2 id="how-phases-fit-title">How the three phases fit together</h2>
    <p>We need to establish three things: that the layer can produce defensible guidance, that the guidance helps with a real change, and that interaction during work adds further value. Each phase examines one of these questions.</p>
    <div className="story-step"><span aria-hidden="true">01</span><div><h3>First, find out what guidance the layer produces.</h3><p>Give an agent a defined set of project evidence and ask it to propose rules. That agent is the <strong>drafter</strong>. A separate <strong>verifier</strong> checks whether its claims are supported. An independent assessment then examines the guide and the verifier’s decisions, including mistakes, missing rules and valid exceptions.</p><p>This gives us an assessed guide. It tells us whether the guidance is defensible in the tested cases, but not whether it helps someone write code.</p></div></div>
    <div className="story-step"><span aria-hidden="true">02</span><div><h3>Then, test whether the guide helps with coding.</h3><p>Ask agents to make the same historical changes. One group works from the project sources alone; another receives the same sources plus the guide. Both get ordinary reviews under the same rules. We independently assess their code and compare the full cost, including preparing the guide.</p><p>This tells us whether supplying guidance improves the work enough to justify its effort. It still does not tell us whether an interactive layer is needed.</p></div></div>
    <div className="story-step"><span aria-hidden="true">03</span><div><h3>Finally, test consultation and checking during work.</h3><p>Add a third group that can consult the layer while it works. A <strong>checker</strong> can ask the agent to explain how its next action respects the guidance and require a correction when necessary. Compare all three groups together, with matched review rules and budgets.</p><p>This tests whether interaction helps beyond a fixed guide and ordinary review. We also assess the checker, including cases where it misses a problem or interrupts valid work.</p></div></div>
    <p className="story-conclusion">These are three parts of the first trial. After each part, we can proceed, revise the method or stop. A negative result is useful evidence too. Together, the results can support a conclusion about the tested cases; they cannot establish that every project needs the layer.</p>
    <p className="story-limits">There is no project owner available to approve new rules, and a model may already know the public code. We will report those limits. A separate study on fresh cases, or work on production approval and maintenance, would need its own decision after this trial.</p>
  </section>
  <PhasePlans guidance={<GuidancePlan/>} use={<UsePlan/>} interaction={<InteractionPlan/>} reference={<FullMethod/>}/>
</Shell>}
