import { RuntimeDiagram } from './runtime-diagram';
import { RuntimeOverview } from './runtime-overview';
import { DetailGroup, Disclosure } from './details';
import { PageLink } from './page-link';
import { ProductionDifference } from './production-difference';

export function TechnicalSetup(){return <section className="section-block" id="technical-setup">
  <div className="section-heading"><span className="section-no">05</span><div><span className="eyebrow">TECHNICAL SETUP</span><h2>How the components work together</h2></div></div>
  <p className="section-intro">The experiment runner is a program that coordinates the work. It gives each agent the files it may read and passes permitted questions and review decisions between them.</p><p className="section-intro">The runner also controls when code can execute and records what happened. Each agent has a separate working environment. The runner controls the connections between those environments.</p><p className="section-intro">The proposed setup runs tools and code inside a virtual machine, or VM. A container inside that VM places further restrictions on the work. The AI models themselves run at the provider, in separate sessions managed by the runner.</p>

  <ProductionDifference production="A deployed layer would need controlled access to current project systems, organisational permissions and approved guidance. The exact integrations and isolation design would depend on that environment." poc="The proposed runner uses isolated roles, an offline VM and containers, restricted file transfers and hidden assessment records to control this experiment. Separate model sessions keep probe and evaluation material out of coding attempts." limit="The selected research setup is not a production deployment recommendation. Passing its boundary tests would establish only the protections actually tested, not general safety or readiness for organisational use."/>
  <p className="section-intro">This is the proposed setup for the complete coding trial. Phase 1 starts with controlled reading for the drafter, verifier and guidance assessor. It does not need the coding agents or interactive checker. If a tool is allowed to execute code during source inspection, the relevant execution protections must be tested before that tool is enabled.</p>
  <RuntimeOverview/>

  <RuntimeDiagram/>

  <section className="technology-section" id="tools-technologies" aria-labelledby="tools-technologies-title">
    <h3 id="tools-technologies-title">Tools and technologies</h3>
    <p>The experiment needs tools for coordination, model access, isolation, assessment and record keeping. The table names the products and libraries selected for the proposed implementation and identifies the remaining choices. The <PageLink className="text-link" href="/progress#technical-status">H04 prototype’s implemented tools</PageLink> are documented on Progress &amp; findings.</p>
    <table className="technology-table">
      <caption className="sr-only">Proposed technologies, their purpose and selection status</caption>
      <thead><tr><th scope="col">Component</th><th scope="col">Technology and reason</th><th scope="col">Choice</th></tr></thead>
      <tbody>
        <tr><th scope="row">Experiment runner</th><td><strong>CPython 3.12: asyncio and subprocess.</strong> These utilities can dispatch work and call VBoxManage. The extent of custom coordination code remains subject to the playbook tooling review.</td><td>Proposed; scope under review</td></tr>
        <tr><th scope="row">Record validation</th><td><strong>Pydantic 2.</strong> Strict schemas reject unknown fields and wrong types. Separate controller checks enforce byte limits, path permissions, role identity and state transitions.</td><td>Chosen for implementation</td></tr>
        <tr><th scope="row">Virtual machine</th><td><strong>Oracle VirtualBox 7.2 with VBoxManage.</strong> The controller creates a disposable clone, starts it and forcibly stops it when required. Host compatibility must be tested.</td><td>Chosen; compatibility gate</td></tr>
        <tr><th scope="row">Guest system</th><td><strong>Ubuntu Server 24.04 LTS, amd64.</strong> A minimal Linux guest holds the launcher and preinstalled dependencies. All VM network adapters are disabled during execution.</td><td>Chosen for implementation</td></tr>
        <tr><th scope="row">Containers</th><td><strong>Rootless Podman with crun.</strong> Linux cgroup v2 enforces resource limits; seccomp restricts system calls. Each tool batch has a private workspace, no network and no exposed runtime socket.</td><td>Chosen; enforcement to test</td></tr>
        <tr><th scope="row">Input transfer</th><td><strong>pycdlib.</strong> Python builds an ISO containing only the permitted job pack. VirtualBox attaches it as an optical disk that the guest can read but cannot change. No host folder is shared.</td><td>Chosen for implementation</td></tr>
        <tr><th scope="row">Output transfer</th><td><strong>VirtualBox virtual serial port + pywin32.</strong> A Windows named pipe carries bounded JSON results. pywin32 supplies Windows pipe and APIs for access controls; the controller treats every result as untrusted.</td><td>Chosen; transport to test</td></tr>
        <tr><th scope="row">Agent access</th><td><strong>Separate role contexts through a controlled model gateway.</strong> Assess LiteLLM / Portkey before deciding what custom gateway code is needed. Provider, model IDs and adapter remain open. Browsing supplied by the provider, execution and shared memory are excluded.</td><td>Provider and models to select</td></tr>
        <tr><th scope="row">Assessment</th><td><strong>Python behaviour checks and pinned project tests.</strong> H04 uses HTTPX MockTransport and custom assertions. Python unittest is proposed for controller checks. Assess Promptfoo for evaluation execution and Langfuse for traces and cost records; model assessors still require separate qualification.</td><td>H04 checks exist; full suite to build</td></tr>
        <tr><th scope="row">Records and credentials</th><td><strong>JSON, SHA-256, Git for Windows and Git Credential Manager.</strong> The design uses a public GitHub repository and a separate private repository. Windows Credential Manager keeps Git credentials local; pywin32’s win32cred API will read separately stored model credentials.</td><td>Private repository and runner storage setup pending</td></tr>
      </tbody>
    </table>
    <p><strong>Tooling review:</strong> the <a className="text-link" href="https://yspbob.github.io/AI-Playbook/AI_Engineering_Playbook.html#2-infrastructure-platform" target="_blank" rel="noreferrer">playbook recommends existing products for common platform capabilities</a>. The design must compare its gateway, evaluation and tracing needs with those products and explain each adoption or departure. LiteLLM, Portkey, Promptfoo and Langfuse are candidates for that review. None has been adopted or installed for the runner. Python utilities may still handle the coordination specific to this experiment.</p>
    <p className="caption">The selected products still need installation and testing. We must first show that they work together and enforce the intended access restrictions.</p><p className="caption">Before execution, we will record the exact software versions, saved environment identifiers and settings. Before qualifying a model for a role, we will also fix its settings. Each run record will include what is needed to reproduce it.</p>
  </section>

  <section className="technology-section" id="containers-and-machines" aria-labelledby="containers-and-machines-title">
    <h3 id="containers-and-machines-title">Run on one qualified machine</h3>
    <p>The coding phases will run on one qualified Windows machine. The proposed setup is sized to fit the 32 GB laptop. Editing the project from either machine can continue through GitHub without moving experimental execution between them.</p>
    <ul className="plain-list">
      <li><strong>Separate the agents.</strong> Each role has its own model context, permitted input pack and tool workspace. The controller passes only authorised submissions and review messages. Shared memory, retrieval stores and direct connections between agents are excluded; assessment answers stay outside working roles.</li>
      <li><strong>Prepare a clean environment.</strong> Install pinned dependencies before execution, then disable the VM’s network adapters. The containers run tools and generated code; the Windows controller makes model calls through a separate gateway.</li>
      <li><strong>Limit every transfer.</strong> Supply permitted files on a disk image that the guest cannot change. Collect bounded results through a virtual serial connection checked by the controller. This interface is part of the boundary that must be tested.</li>
      <li><strong>Reset between tool batches.</strong> Each bounded batch uses a fresh VM and container. Only checked workspace files carry forward. Execution stops before the next review, and environments share no writable caches.</li>
      <li><strong>Keep each comparison on the selected host.</strong> Run all three groups on that machine and retain protected records. If experiments later move to another host, it must first pass the same required tests and receive verified records. That transfer capability is not a gate for the first trial.</li>
    </ul>
    <p>The <a className="text-link" href="https://github.com/yspbob/interpretation-layer-poc/blob/main/research/development/isolated-runner-design-v0.1.md" target="_blank" rel="noreferrer">detailed runner design</a> specifies the container restrictions, transfer limits, provisional resource profile, failure handling and workflow for private records. Compatibility and containment must be demonstrated on any host before experiments run there. Each phase needs a qualified boundary for the capabilities it actually uses.</p>
  </section>

  <DetailGroup>
    <Disclosure id="technical-inputs" title="What does each role receive?">
      <p>An input pack contains the files a role is allowed to read. Its manifest lists those files and their digital fingerprints, called hashes. The runner uses these to check that the contents have not changed before starting a fresh session.</p>
      <ul className="plain-list">
        <li><strong>Drafter and verifier:</strong> the permitted project evidence and instructions. The verifier also receives the proposed claims. Neither receives the later change task or final assessment.</li>
        <li><strong>Coder and reviewer:</strong> the task, permitted sources and applicable project instructions. The groups with prepared guidance also receive the same saved guide. Reviewers receive the submitted plan and changes; they do not receive the coder’s private reasoning.</li>
        <li><strong>Assessment roles:</strong> a guidance assessor checks the frozen guide against separately prepared evidence; an intervention assessor checks review decisions against what was knowable at the time. These records stay outside the live roles.</li>
        <li><strong>Final code judge:</strong> the code to assess, task requirements, guardrail criteria and independently produced test observations. The judge is not told whether the code came from a historical change or an agent, which comparison group produced it, or which model was used.</li>
      </ul>
      <p>The project’s actual <code>AGENTS.md</code> files, including applicable instructions for the relevant directories, are taken from the backtest’s starting revision. The same applicable files are supplied across all three groups. Their absence is recorded rather than filled with invented instructions. If they state a tested rule, that case is classified as using documented guidance.</p>
    </Disclosure>
    <Disclosure id="technical-execution" title="How are plans, reviews and model calls coordinated?">
      <p>The runner records whether an attempt is waiting for a plan, a review or a correction, is allowed to work, or has stopped. It accepts only messages permitted at that stage.</p><p>A substantial change of approach sends the attempt back to plan review. A required decision that cannot be settled, an exhausted allowance or a failed access boundary triggers the specified stop procedure.</p>
      <p>During implementation, incoming code submissions are checked against the approved plan. The runner pauses at configured review points and on detected material changes, then passes the relevant plan and code to the reviewer. Work resumes only after the required decision permits it. The same rules that trigger review and correction limits apply across all three groups. Different approaches can trigger different checks. While review is pending, the runner must block new coding turns and tools that would change files or state.</p>
      <p>A model gateway is the part that sends authorised requests to the model provider and records usage. Credentials stay outside the agent workspace.</p><p>The controller passes only permitted questions, submissions and decisions between roles. An agent cannot use that connection to issue arbitrary commands.</p><p>The gateway accepts requests only for approved model providers and enforces message size limits. It cannot fetch arbitrary websites. A correctly formatted message still needs its permissions and content checked.</p>
      <p>Candidate code runs separately from the controller and the full assessment store. Common task checks may return permitted feedback during work. Final evaluation uses a separate assessment path after the attempt ends. The evaluator must test resistance to modified tests and forged success reports, rather than trust a candidate’s claim that its checks passed.</p>
    </Disclosure>
    <Disclosure id="technical-isolation" title="How is access beyond the test environment restricted?">
      <p>The design requires agents to have no general access to the host machine, other runs or external services. The runner still needs narrowly defined routes to supply inputs, pass permitted review messages and collect outputs. Those interfaces are part of the isolation boundary and must be tested too.</p>
      <ul className="plain-list">
        <li><strong>Restrict and record communication.</strong> Permitted exchanges pass through the external controller. Other routes must be blocked, including indirect communication through shared services.</li>
        <li><strong>Minimise and test exposed services.</strong> Each agent receives only the tools, storage and network capabilities its task requires. Every exposed capability is reviewed for unintended access. The controller and gateway are trusted components whose versions, permissions and behaviour must also be tested. Installing dependencies before the run and preventing changes to them removes the need for a live package service during execution.</li>
        <li><strong>Protect the host and assessment.</strong> Host files, credentials and administrative controls stay outside agent access. Workspaces and caches cannot provide shared writable channels. The controller, stop mechanism and assessment records remain protected from agent writes.</li>
        <li><strong>Test attempted boundary crossings.</strong> Controlled probes check file access, communication between roles and runs, direct and indirect network access, and attempts to alter enforcement. The relevant checks are repeated after environment changes. Detected failures stop affected runs and preserve the evidence.</li>
      </ul>
      <p>The Hugging Face incident demonstrated how a shared package service could become an unintended message board and a route to the internet. It motivates reviewing all exposed services, not only package installation. <a className="text-link" href="https://openai.com/index/hugging-face-incident-and-the-road-ahead/" target="_blank" rel="noreferrer">OpenAI’s account</a> and <a className="text-link" href="https://huggingface.co/blog/agent-intrusion-technical-timeline" target="_blank" rel="noreferrer">Hugging Face’s technical account</a> describe the incident.</p>
      <p>The runner must record its isolation boundaries and the results of tests that attempt to cross them. These tests establish protection against the routes examined, with remaining limitations stated. They cannot guarantee that escape is impossible.</p>
      <p><strong>Proposed implementation:</strong> VirtualBox provides the outer VM boundary, with rootless Podman containers inside an Ubuntu guest. Input images that cannot be changed and serial output with size limits replace shared folders and guest networking. The virtualisation software and the programs that transfer data could still contain vulnerabilities. Any claim about isolation must state which routes were tested and what remains uncertain.</p>
    </Disclosure>
    <Disclosure id="technical-records" title="What makes a run inspectable and repeatable?">
      <p>Each run will record exactly what the agents received and returned. It will also record the software and model settings, tool activity, review decisions, corrections, stops and resource use.</p><p>The controller keeps those records outside agent access. It saves confidential records to the separate private repository and verifies the save before work continues on the other machine. A failed save must be recorded, and work that depends on the missing evidence cannot continue.</p><p>Returned files and messages are treated as untrusted. The runner checks their destination, size and order before accepting them. It also checks whether links or files inside an archive could reach beyond the allowed folder.</p>
      <p>The assessment reports task correctness separately from compliance with project rules. It records improvements over the historical code, new violations and questions the evidence cannot settle.</p><p>Public reports exclude credentials and hidden assessment material. Models, budgets, scoring weights and acceptance limits are fixed before the relevant scored runs.</p>
    </Disclosure>
  </DetailGroup>
  <p className="caption">The method defines the required behaviour. <PageLink className="text-link" href="/progress#technical-status">Progress &amp; findings records component readiness and open technical choices.</PageLink></p>
</section>}
