'use client';
import { sitePath } from '../site-path';

import { PageLink } from '../page-link';

import { ArrowRight, Check, ShieldQuestion, ArrowUpRight, Clock3, GitBranch } from 'lucide-react';
import { DetailGroup, Disclosure, EvidenceExplorer, EvidenceDownloads, RepositoryCards } from '../details';
import evidence from '../evidence.json';
import { caseSummaries } from '../case-summaries';

const phases=[
{id:'scope',title:'Decide what the experiment should test',state:'Complete',body:'The playbook review established the question: does preparing guidance help an agent make a later change, and does checking its use add further value? Owner approval remains outside this technical test.'},
{id:'inventory',title:'Find suitable cases in real projects',state:'Complete',body:'The inventory review covered 84 candidate records across four projects. Of these, 52 advance to development, covering 39 groups of related decisions. They still need working tasks and reliable scoring before they can become experiments.'},
{id:'prepare',title:'Build and check the experimental procedure',state:'Next',body:'The component input and output rules and the first scripted example now exist. Next we need to build and test the isolated runner. We will then prepare further cases and test each assessor on examples kept separate from its development work. Preparation is not complete.'},
{id:'pilot',title:'Run a small trial to test the setup',state:'Not started',body:'The pilot will compare the three ways of working on a small set of tasks to check task quality, scoring reliability and cost records. Material used to improve the setup will stay out of the main trial.'},
{id:'freeze',title:'Fix the rules for the main trial',state:'Not started',body:'The final cases, number of runs, scoring rules and resource limits must be fixed before the main results are seen. This includes the improvement needed to justify the added work and how related cases will be analysed.'},
{id:'confirm',title:'Run the main comparison',state:'Not started',body:'The agreed comparisons will run in separate controlled environments. Unsuccessful and unfinished attempts remain in the record, and the work is assessed independently.'},
{id:'conclude',title:'Use the results to revise the playbook',state:'Not started',body:'The findings will explain where the layer helped, where it did not and what it cost. Conclusions must reflect uncertainty and stay within what these projects and tasks can establish.'},
];
const risks=[
{id:'judge',title:'The judges have not passed an independent validation test',tag:'Open',why:'A judge could accept convincing but incorrect work, reject valid exceptions, or favour one group. The working plan specifies separate tests for verification, runtime review and later assessment of guidance, code and interventions. None has completed qualification.',next:'Prepare examples where evidence justifies the expected decisions. Use different groups of related rules to develop the judges and to test them. Set acceptable error rates and the amount of validation evidence needed before seeing the results. Measure missed violations and false objections separately. Keep ambiguous cases unresolved when independent evidence cannot settle them.'},
{id:'interaction',title:'The checking procedure is only partly implemented',tag:'Open',why:'The scripted case exercises correction limits and detects known changes to response cleanup. It does not show that a model checker catches violations or accepts exceptions, or that an isolated runner enforces the decisions.',next:'Build the controlled run and test the checker on both valid and invalid plans. Validate its permitted inputs, the handling of plan changes and the correction limit. Give comparison conditions equivalent review opportunities and account for all checking effort.'},
{id:'containment',title:'We have not shown that agents stay within their permitted environment',tag:'Required before model runs',why:'The existing checks on permitted file requests do not establish containment. Neither host isolation nor protection against indirect routes through supporting services has been validated. A shared package service was one route in the Hugging Face incident; other tools and services may expose different routes.',next:'Build the proposed offline virtual machine and container setup. List every tool and connection exposed to an agent. Test attempts to reach host files, other roles, other runs and the internet, including indirect routes through services.\n\nNeither machine has passed these tests. A detected failure must stop the affected runs and preserve the evidence.'},
{id:'instructions',title:'Project instructions need checking at each task’s starting version',tag:'Open',why:'All three groups will receive each project’s actual AGENTS.md files from the starting revision, including applicable instructions for the relevant directories. Their presence, scope and disclosure of tested rules have not yet been audited for the historical cases.',next:'Record the applicable instruction files and their exact contents, or record that no files exist. Give the same files to all three groups. If they state the rule being tested, classify the case as using documented guidance. Keep real project instructions available to the group using sources alone.'},
{id:'leakage',title:'An agent may already know the code or find the rule elsewhere',tag:'Open',why:'Containers can restrict runtime access, but cannot erase model training knowledge. Comments, error messages, examples and dependencies may also reveal a withheld rule.',next:'Set the questions and scoring rules for the two familiarity checks before running them. Keep all outcomes and record what they imply for case selection. A lack of detected recall cannot prove that the model has never seen the code.\n\nAlso inspect the permitted files for material that reveals the withheld rule. Access restrictions remain necessary even when we check for prior familiarity.'},
{id:'gold',title:'The historical implementation also needs assessment',tag:'Open',why:'The actual code may violate the applicable guardrails. Matching it exactly could penalise an agent that makes a justified improvement. Documentation can also conflict with the code or omit a legitimate exception.',next:'Assess historical and agent implementations separately for task correctness and guardrail compliance using the same independently established criteria. Credit an avoided historical violation when the agent still completes the task correctly. Define points and weighting before scored runs; this comparison has not yet been implemented or validated.'},
{id:'sample',title:'Several cases can test the same decision',tag:'Open',why:'The 52 candidates cover 39 groups of related decisions. Six candidates were already used during development. The remaining 46 cover 33 groups. These relationships matter when deciding how much independent evidence the trial can provide.',next:'Keep tasks about the same underlying decision together in the analysis, including repeated attempts. Count a task toward the trial only after it passes the case checks. Use the pilot to estimate how much results vary, then choose a size for the main trial that can detect the improvement worth pursuing.'},
{id:'deps',title:'Some rules depend on libraries we have not yet checked',tag:'Open',why:'Six records remain deferred, including revision relations, search internals, soft deletion, audit attribution and transport retries.',next:'Pin and inspect the relevant dependencies, or exclude these cases from the pilot with the reason recorded.'},
{id:'scope',title:'A technical success cannot show that an owner approves the guidance',tag:'Scope limit',why:'Published decisions supply references. They do not certify the layer’s new proposals or reveal undocumented organisational intent.',next:'Keep owner acceptance, production renewal and broader organisational value separate from the technical POC verdict. This first iteration minimises external dependencies; later iterations could include owners and maintenance if the remaining questions require them.'},
];

export function ProgressView(){return <>
<div className="page-heading"><span className="eyebrow">PROGRESS / 10 SEPTEMBER 2026</span><span className="reading-time">Inventory reviewed {evidence.updated}</span></div>
<section className="progress-intro"><div><div className="status-line"><span className="pill green"><Check size={13}/>Evidence reviewed</span><span className="pill neutral">Pilot not started</span></div><h1>The first example is <em>ready to inspect.</em></h1><p className="lead">One HTTPX development task has been rehearsed with correct solutions, deliberate mistakes and scripted review decisions. Its 25 behaviour checks gave the expected results. No AI component has been tested or qualified yet.</p><a href="#next-work" className="text-link">See the example and the next step <ArrowRight size={16}/></a></div><aside className="credibility-card"><div className="credibility-heading"><ShieldQuestion size={21}/><span className="eyebrow">CAN THE RESULTS BE TRUSTED?</span></div><h2>The sources are recorded.<br/>The scoring still needs validation.</h2><p>No blinded comparison has run. Reliable results require validated judges, test tasks and restrictions on what each agent can see.</p><a href="#credibility" className="text-link">See what has been checked <ArrowRight size={16}/></a></aside></section>
<div className="metrics"><Metric value="84" label="Examples reviewed" note="Reviewed for possible use in the experiment"/><Metric value="52" label="Candidates for the pilot" note="Some test the same underlying decision"/><Metric value="4" label="Repositories" note="All Python; three use Django"/><Metric value="0" label="Agent comparisons run" note="The layer’s benefit has not been tested"/></div>
<section className="next-work" id="next-work" aria-labelledby="next-work-title">
  <span className="eyebrow">DEVELOPMENT MILESTONE / 8 SEPTEMBER 2026</span>
  <h2 id="next-work-title">One response, two valid ways to close it</h2>
  <p>HTTPX is a Python HTTP client. The first task reads only the start of a response, then releases it while keeping the client open. The new contracts define three distinct roles:</p>
  <ul className="next-work-roles">
    <li><strong>The verifier</strong> checks whether the evidence supports the guidance drafted by the layer.</li>
    <li><strong>The checker</strong> questions the agent’s plan and actions while it works, and decides whether it can proceed.</li>
    <li><strong>The judge</strong> assesses the finished work against the reference evidence after the attempt ends.</li>
  </ul>
  <p>Two solutions released the response correctly. One used a context manager, which handles cleanup automatically. The other closed the response explicitly in a finally clause, so cleanup would still happen after an error.</p><p>The checks caught code that never closed the response and code that closed it only when nothing went wrong. Testing an empty response alone would have missed those mistakes. The record includes the exact inputs, scripted decisions and observed behaviour.</p>
  <p className="next-work-limit">The review decisions were written in advance. They were not made by a model. Checks on which files the program could request passed, but they do not establish that a container can isolate an agent.</p><p className="next-work-limit">The next implementation work is to run roles separately, test their access restrictions and enforce review pauses. Independent tests of the judges will use different examples.</p>
  <a className="text-link" href="https://github.com/yspbob/interpretation-layer-poc/tree/main/research/development/h04-response-lifetime" target="_blank" rel="noreferrer">Inspect the case, code and recorded checks <ArrowUpRight size={16}/></a>
</section>
<section className="section-block" id="technical-status">
  <div className="section-heading"><span className="section-no"><GitBranch size={17}/></span><div><span className="eyebrow">TECHNICAL READINESS</span><h2>What is built and what still needs validation</h2></div></div>
  <p className="section-intro">The procedure has not run as an isolated model trial. The existing work is a scripted development rehearsal. <PageLink className="text-link" href="/#technical-setup">The Experiment explains the planned technical setup.</PageLink></p>
  <div className="technical-status-list">
    <div><h3>Input packs and component contracts</h3><p>The H04 example prepares separate input files for each role and records file fingerprints so changes can be detected. It also specifies what each component may receive and return. The audit of project instructions and historical case packs remain to be prepared.</p></div>
    <div><h3>Runner and review checkpoints</h3><p>The rehearsal checks correction limits, stopping and known changes to response cleanup.</p><p>The runner still needs to start isolated work, validate all incoming records and enforce pauses. Detecting other substantial changes of plan also remains to be built and tested.</p></div>
    <div><h3>Isolation and model gateway</h3><p>Filesystem and network containment are unvalidated. VirtualBox, Ubuntu Server 24.04 LTS and rootless Podman are proposed, with input images that cannot be changed and serial output with size limits. Runtime setup, controller interfaces and model gateway remain unimplemented. No model has been called in the redesigned experiment.</p></div>
    <div><h3>Independent evaluation</h3><p>In H04, 25 comparisons produced the outcomes specified in advance by the case author. This checks the scripted example. It does not establish that an AI judge is reliable.</p><p>The four calibration records provide starting material for developing assessment. We still need to build and test assessment of guidance and review decisions, qualification of model judges, and scoring of historical implementations.</p></div>
  </div>
  <div className="prototype-tools" id="prototype-tools">
    <h3>Tools implemented in the H04 prototype</h3>
    <ul className="plain-list">
      <li><strong>Python 3.12 and asyncio</strong> run the scripted case and asynchronous response checks. The recorded execution used Python 3.12.14 on Windows.</li>
      <li><strong>HTTPX MockTransport</strong> supplies controlled responses without outbound requests. The custom Python checks inspect cleanup behaviour; a narrow comparison of code structure detects known changes in the authored examples.</li>
      <li><strong>JSON and SHA-256</strong> record results and identify exact input files. Git and GitHub preserve the reviewed public source and evidence.</li>
    </ul>
    <p>The prototype has no model API integration, VM/container execution or protected storage for assessment records. Its tools demonstrate the scripted case only. The <a className="text-link" href="https://github.com/yspbob/interpretation-layer-poc/tree/main/research/development/h04-response-lifetime" target="_blank" rel="noreferrer">H04 record</a> includes dependency pins, observed versions and reproduction commands; <PageLink className="text-link" href="/#tools-technologies">The Experiment lists the proposed technology choices for the full experiment.</PageLink></p>
  </div>
  <p>The experiment is designed to fit on the 32 GB laptop and to run locally on either machine. The 64 GB home PC does not need to stay on.</p><p>A separate private GitHub repository is planned for confidential records but has not been created. VirtualBox still needs a compatibility check on the laptop, which runs Windows Home with an active Windows hypervisor. The home PC has not been inspected.</p>
  <p>A reusable prerequisite check now records local machine capabilities. It does not install the runtime or establish containment. The <a className="text-link" href="https://github.com/yspbob/interpretation-layer-poc/blob/main/research/development/isolated-runner-design-v0.1.md" target="_blank" rel="noreferrer">runner design</a> specifies complete comparison blocks on one host, verified private saves before switching and separate boundary tests on both machines. The controls for execution and saving private records remain to be built.</p><p><PageLink className="text-link" href="/#runtime-architecture">The deployment diagram</PageLink> names the selected products and separates agent contexts from code containment; the additional schema and transport libraries have not been installed for the runner. </p><p>The custom gateway, evaluation and tracing choices also need review against the playbook’s recommended products; none of those alternatives has been adopted.</p>
  <p>The plan now explains how we will check for signs that a model already knows the public code. Those checks have not run. Their questions, scoring rules and number of attempts still need to be fixed.</p><p>It also explains how we will measure whether a guide recovers its preparation cost across different tasks. Cost recording and the choice of tasks sharing each guide remain unfinished.</p><p><strong>The budget selection procedure is recorded.</strong> We will use separate development tasks to measure costs before fixing the allowance for scored comparisons. The overall spending ceiling, candidate amounts and selection criteria remain open. No budget calibration has run. <PageLink className="text-link" href="/#budget-selection">Read how we will choose the budget.</PageLink></p>
  <p className="caption">Next: review the proposed tools against the playbook’s recommendations. Then install and test the isolated runner on the laptop without calling models. Independent tests of the assessment components must use different case families before any authorised model comparison.</p>
</section>
<section className="scope-note" id="pilot-scope-status"><span>Pilot scope clarified</span><div><p>The first pilot will ask agents to repeat real changes from public projects. Each task needs clear requirements and supporting evidence. A model may already know that code, so the results cannot prove it discovered every rule from unfamiliar files.</p><p>If the evidence cannot settle a central requirement, that case stays out of scoring. We assess the historical implementation too, because it may contain mistakes.</p><p>Case selection and independent tests of the judges remain unfinished. Zero model comparisons have run. <PageLink className="text-link" href="/#pilot-scope">Read the scope and limitation.</PageLink></p></div></section>
<section className="section-block" id="process">
  <div className="section-heading"><span className="section-no"><GitBranch size={17}/></span><div><span className="eyebrow">THE WHOLE PROCESS</span><h2>Current position in the process</h2></div></div>
  <ol className="study-roadmap" aria-label="Study stages">
    {phases.map((p,i)=><li className={`roadmap-stage ${p.state==='Next'?'roadmap-next':''}`} key={p.id} aria-current={p.state==='Next'?'step':undefined}>
      <span className={`roadmap-number ${p.state==='Complete'?'roadmap-done':''}`} aria-hidden="true">{p.state==='Complete'?<Check size={18}/>:i+1}</span>
      <div><div className="roadmap-heading"><h3>{p.title}</h3><span className={`pill ${p.state==='Complete'?'green':p.state==='Next'?'amber':'neutral'}`}>{p.state}</span></div><p>{p.body}</p></div>
    </li>)}
  </ol>
</section>
<section className="section-block" id="credibility"><div className="section-heading"><span className="section-no">01</span><div><span className="eyebrow">CHECKS BEFORE THE TRIAL</span><h2>Checks completed so far</h2></div></div><div className="readiness-grid"><div className="readiness-list">{[['Fixed copies of the code and source links','Recorded','green'],['Reasons for including or excluding examples','Recorded','green'],['Earlier source behaviour probes','15 passed during preparation','blue'],['First scripted development case','25 behaviour expectations reproduced','blue'],['Agent containment and checks for escape routes','Not implemented or validated','amber'],['Check for answers in the allowed inputs','Not complete','amber'],['Working tasks and reliable scoring','Not validated','amber'],['Method for the main trial','Not frozen','neutral']].map(([name,state,color])=><div key={name}><span>{name}</span><span className={`pill ${color}`}>{state}</span></div>)}</div><div className="interpretation-note"><span className="eyebrow">WHAT THESE CHECKS ESTABLISH</span><p>Checks have covered source behaviour and one case rehearsal.</p><span>The earlier 15 probes and the new 25 case checks confirm specific behaviours. Scripted review decisions do not establish whether an AI judges correctly or whether the layer improves engineering work. No trial has run in isolated containers.</span></div></div></section>
<section className="section-block" id="findings"><div className="section-heading"><span className="section-no">02</span><div><span className="eyebrow">USEFUL FINDINGS</span><h2>Findings so far</h2></div></div><DetailGroup>
<Disclosure id="docs" title="Sometimes the documentation and code disagree" summary="Examples from HTTPX, NetBox and Paperless."><p>HTTPX’s guide says that setting cookies separately on each client request is unsupported. The pinned implementation still accepts them, with a warning. The review also identified a disagreement about how HTTPX chooses the text encoding when a response does not specify one. Local checks confirmed these behaviours.</p><p>There are similar cases elsewhere. Some NetBox code uses exceptions to its general guidance for converting objects into API responses. In Paperless, the pinned code for editing PDFs schedules a new document version, which complicates the guide’s description of editing the original.</p><p><strong>Implication:</strong> the assessment needs to establish whether an answer explains the evidence correctly. Both the historical implementation and the agent’s work need assessment against the applicable rules and required behaviour. Avoiding a historical violation should count in the agent’s favour when the task remains correct.</p><Source caseId="H11"/><Source caseId="P14"/></Disclosure>
<Disclosure id="boundaries" title="Exceptions make the tests more useful" summary="A rule may be correct in one part of the system and unnecessary in another."><p>NetBox needs to save an object’s previous state before an edit, but parts of the framework already do that. An agent has to know when extra work is needed and when it is not. Other cases include exceptions to a general setting, or a component that deliberately leaves a job to another component.</p><p><strong>Implication:</strong> a useful test should include a change that breaks the rule and an alternative that is allowed. Recognising a familiar function name would establish much less.</p><Source caseId="N12"/><Source caseId="P13"/><Source caseId="H10"/></Disclosure>
<Disclosure id="supply" title="Several cases test the same underlying decision" summary="The 52 candidates cover 39 groups of related decisions."><p>Of the 84 examples reviewed, 52 are candidates for further development. Fifteen are control cases covering documentation conflicts, enforcement gaps and claims that the available evidence cannot establish. Six need more investigation, four are simple checks for developing the scoring, three overlap with another case, and four were rejected. Six of the 52 candidates had already been used in the initial development work.</p><p><strong>Implication:</strong> the inventory provides material for the pilot, but the number of rows does not establish that the main trial will be large enough. We must decide what improvement the main trial needs to detect and how much evidence that requires. Several cases about the same decision cannot be counted as if they were unrelated.</p><a className="text-link" href={sitePath("/evidence/cross-repository-inventory-review.md")} download>Read the inventory assessment <ArrowUpRight size={16}/></a></Disclosure>
</DetailGroup></section>
<section className="section-block" id="implementation-takeaways">
  <div className="section-heading"><span className="section-no">↗</span><div><span className="eyebrow">LESSONS FOR IMPLEMENTATION</span><h2>Design takeaways to carry into production</h2></div></div>
  <p className="section-intro">These ideas came from planning the POC. We are keeping them so that they can inform a practical implementation. They are not experimental results.</p>
  <DetailGroup>
    <Disclosure id="reuse-takeaway" title="A guide may earn its preparation cost across several changes" summary="Measure repeated use, rather than judging the whole cost from the first task."><p>Preparing a guide may be worthwhile even when its first use does not recover the cost. We will follow its cost and usefulness across different tasks that can share it.</p><p>We will compare those tasks with work done from sources alone. No savings have been measured yet. <PageLink className="text-link" href="/#fair-comparison">Read the planned cost comparison.</PageLink></p></Disclosure>
    <Disclosure id="maintenance-takeaway" title="Costs and outcomes can tell a human when guidance needs review" summary="An economic reason for review, alongside changes in the code or requirements."><p>A production dashboard could show how often guidance applies, what it costs to prepare and check, whether it helps avoid mistakes, and whether it causes unnecessary objections. It should show evidence and uncertainty alongside estimated break even.</p><p>A responsible human could decide whether to retain, revise or combine guidance, change how it is enforced, or retire it where appropriate. A mandatory obligation does not disappear because it saves little time.</p><p>Several rules may help with the same change, and some preparation work may serve them all. A cost or saving should not be counted again for every rule.</p><p>We will start by assessing a guide or group of related rules together. The evidence may not support a precise return for each individual rule.</p><p>The POC can collect useful signals for later decisions. Building a production dashboard and maintaining live guidance are outside this pilot.</p></Disclosure>
  </DetailGroup>
  <p><a className="text-link" href="https://github.com/yspbob/interpretation-layer-poc/blob/main/research/implementation-takeaways.md" target="_blank" rel="noreferrer">Read the growing record of implementation takeaways <ArrowUpRight size={16}/></a>. Each entry records its source, evidence status, practical implication and next step, including limits and adverse findings.</p>
</section>
<section className="section-block" id="risks"><div className="section-heading"><span className="section-no">03</span><div><span className="eyebrow">RISKS & ISSUES</span><h2>Issues still to resolve</h2></div></div><DetailGroup>{risks.map(r=><Disclosure key={r.id} id={r.id} title={r.title} summary={r.tag}><div className="detail-columns"><div><h3>Why it matters</h3><p>{r.why}</p>{r.id==='containment'&&<p><a className="text-link" href="https://openai.com/index/hugging-face-incident-and-the-road-ahead/" target="_blank" rel="noreferrer">Read the incident account <ArrowUpRight size={16}/></a></p>}</div><div><h3>Next action</h3><>{r.next.split("\n\n").map((paragraph,i)=><p key={i}>{paragraph}</p>)}</></div></div></Disclosure>)}</DetailGroup></section>
<section className="section-block"><div className="section-heading"><span className="section-no">04</span><div><span className="eyebrow">DECISIONS STILL TO MAKE</span><h2>Before the pilot can run</h2></div></div><p className="section-intro">The plan describes how the experiment should work. Before it can run, the controls must be built and tested, the cases and judges must be checked, and the settings below must be fixed. Publishing the design does not complete those steps.</p><div className="decision-list">{[
['01','Before any model calls: can the runner enforce the boundaries?','Build and test the proposed setup on each machine that will run experiments. Show that it restricts inputs, enforces pauses and stops, and controls model access. Test attempts to use forbidden direct and indirect routes. Record the exact setup and results.'],
['02','Before selecting runnable cases: is each assessment defensible?','Identify the code and rules as they stood when each historical task began. Check valid and invalid solutions, inspect project instructions and look for files that reveal hidden answers. Keep authored examples separate from historical tasks. The inventory alone does not complete these checks.'],
['03','Before qualification: what must each assessor pass?','Build separate development and validation families with justified expected assessments. Fix instructions for each role, models, error limits, coverage, sample size and acceptance rules before opening validation results. The verifier must not score its own success.'],
['04','Before the pilot: are the run settings complete?','Use the development calibration to choose the spending allowance, then fix preparation and correction limits. Record which tasks share each guide and how its cost is divided. Also fix when reviews happen, the order of groups, scoring and retry rules, and which scores will be audited. Every required component must have passed its qualification tests.'],
['05','Before confirmation: what result would justify the work?','Use the pilot to decide the main question and measure for the final trial. Specify how much improvement would be worthwhile and how many tasks and repetitions are needed to detect it. Set cost limits and explain how related cases will be analysed. Keep cases used to tune the method out of that final trial.']
].map(([n,title,body])=><div key={n}><span className="section-no">{n}</span><div><h3>{title}</h3><p>{body}</p></div><span className="pill neutral">Open</span></div>)}</div><DetailGroup><Disclosure id="direction" title="The current proposal" summary="The main trial’s method and success criteria have not yet been agreed."><ul className="plain-list"><li>Use NetBox, Wagtail, Paperless-ngx and HTTPX as sources of candidate cases.</li><li>Check interpretations against explicit project records, while keeping owner approval outside this technical test.</li><li>Build a small pilot to check the tasks, information restrictions and scoring before committing to a larger trial.</li><li>Distinguish the value of preparing guidance from the additional value of consulting the layer and checking the agent’s use of it.</li></ul></Disclosure></DetailGroup></section>
<section className="section-block" id="evidence"><div className="section-heading"><span className="section-no">05</span><div><span className="eyebrow">EVIDENCE RECORD</span><h2>Sources and research record</h2></div></div><DetailGroup><Disclosure id="repos" title="Repository coverage" summary="The four pinned snapshots and their roles in the study."><RepositoryCards showCounts/></Disclosure><Disclosure id="inventory" title="Browse all 84 candidate records" summary="Search by topic or repository, or filter by why a case was kept or set aside."><EvidenceExplorer/></Disclosure><Disclosure id="reports" title="Reports and supporting records" summary="Download the assessment, case cards and screening protocol."><EvidenceDownloads/></Disclosure><Disclosure id="history" title="Research activity" summary="First scripted case completed on 8 September; inventory review completed on 5 September."><p>On 8 September, the first HTTPX development case reproduced 25 behaviour expectations, six control checks and 71 denied file requests. No model was called.</p><p>On 9 September, a full website and plan review clarified the assessment roles, historical evidence, matched budgets and readiness gates. It changed the design and explanation, not the experimental results. <a className="text-link" href="https://github.com/yspbob/interpretation-layer-poc/blob/main/research/development/site-plan-review-2026-09-09.md" target="_blank" rel="noreferrer">Read the review and remaining prerequisites.</a></p><div className="activity-list">{[['Broader inventory completed','84 records screened across four repositories. Fifteen new local development checks passed.'],['NetBox feasibility audit completed','Twelve initial cases distinguished recoverable conventions, conflicts, conditional guidance and policies requiring authority.'],['Original POC design reviewed','The review found that reference answers needed independent justification and that the comparison and scoring needed redesign.']].map(([title,body])=><div key={title}><Clock3 size={17}/><div><span className="eyebrow">05 SEP 2026</span><h3>{title}</h3><p>{body}</p></div></div>)}</div></Disclosure></DetailGroup></section>
<div className="route-footer"><span>Read the study’s purpose and planned procedure.</span><PageLink href="/">The experiment <ArrowRight size={18}/></PageLink></div>
</>}
function Metric({value,label,note}:{value:string,label:string,note:string}){return <div className="metric"><span className="metric-value">{value}</span><strong>{label}</strong><p>{note}</p></div>}
function Source({caseId}:{caseId:string}){const c=evidence.cases.find(c=>c.id===caseId)!;return <a href={c.reference.url} target="_blank" rel="noreferrer" className="finding-source">{caseId} · {caseSummaries[caseId]?.title || c.title}<ArrowUpRight size={14}/></a>}
