'use client';
import { sitePath } from '../site-path';

import { PageLink } from '../page-link';

import { ArrowRight, Check, ShieldQuestion, ArrowUpRight, Clock3, GitBranch } from 'lucide-react';
import { DetailGroup, Disclosure, EvidenceExplorer, EvidenceDownloads, RepositoryCards } from '../details';
import evidence from '../evidence.json';

const phases=[
{id:'scope',title:'Decide what the experiment should prove',state:'Complete',body:'We reviewed the playbook and defined the question: does preparing guidance help an agent make a later change, and does checking its use add further value? Owner approval remains outside this technical test.'},
{id:'inventory',title:'Find suitable cases in real projects',state:'Complete',body:'We reviewed 84 candidate records across four projects. We selected 52 for further development, covering 39 groups of related decisions. They still need working tasks and reliable scoring before they can become experiments.'},
{id:'prepare',title:'Build and check the experimental procedure',state:'Next',body:'Start with precise instructions for the verifier, checker and judge, and one complete worked example. Then build further cases, test the information restrictions and validate the components on separate material. This preparation is not complete.'},
{id:'pilot',title:'Run a small trial to test the setup',state:'Not started',body:'Compare the three ways of working on a small set of tasks. Check whether the tasks are useful, the scores are reliable and the costs are recorded. Material used to improve the setup will stay out of the main trial.'},
{id:'freeze',title:'Fix the rules for the main trial',state:'Not started',body:'Before seeing the main results, choose the final cases, number of runs, scoring rules and resource limits. Record how much improvement would justify the added work and how we will analyse related cases.'},
{id:'confirm',title:'Run the main comparison',state:'Not started',body:'Run the agreed comparisons in separate controlled environments. Keep unsuccessful and unfinished attempts in the record, and assess the work independently.'},
{id:'conclude',title:'Use the results to revise the playbook',state:'Not started',body:'Explain where the layer helped, where it did not and what it cost. If the result is uncertain, say so. Keep the conclusions within what these projects and tasks can establish.'},
];
const risks=[
{id:'judge',title:'The judges have not passed an independent validation test',tag:'Open',why:'A judge could accept convincing but incorrect work, reject valid exceptions, or favour one group. The working plan now defines a separate qualification procedure for the guidance verifier, runtime checker and final scorer; none has completed it.',next:'Build examples with defensible reference verdicts, separate rubric development from validation by decision family, and set error limits and required precision before testing. Measure missed violations and false objections separately. Keep ambiguous cases unresolved when independent evidence cannot settle them.'},
{id:'interaction',title:'The proposed checking procedure has not been built or validated',tag:'Open',why:'The pilot proposal now defines a plan check before editing, review of code changes, three possible decisions and a limit of two correction rounds per checkpoint. We have not yet shown that the checker catches violations, accepts valid exceptions or notices an undeclared change of approach.',next:'Build the controlled run and test the checker on both valid and invalid plans. Validate its permitted inputs, the handling of plan changes and the correction limit. Give comparison conditions equivalent review opportunities and account for all checking effort.'},
{id:'leakage',title:'Public-source knowledge and alternative disclosures',tag:'Open',why:'Containers can restrict runtime access, but cannot erase model training knowledge. Comments, error messages, examples and dependencies may also reveal a withheld rule.',next:'Review allowed inputs case by case, record their hashes, and add unpublished semantic variants and renaming controls.'},
{id:'gold',title:'Documentation can disagree with implementation',tag:'Open',why:'The audits found conflicting guidance and enforcement gaps. A single document cannot safely serve as an unquestionable answer key.',next:'Resolve and label each reference, preserve exceptions, and calibrate scoring against valid alternatives and intentional errors.'},
{id:'sample',title:'Case counts overstate independent evidence',tag:'Open',why:'52 advancing rows cover 39 named families. Excluding the original development cases leaves 46 new rows across 33 families.',next:'Group related challenges and repeats, qualify cases before counting them, and size confirmation from the planned effect and observed variability.'},
{id:'deps',title:'Some key behavior sits outside the checkout',tag:'Open',why:'Six records remain deferred, including revision relations, search internals, soft deletion, audit attribution and transport retries.',next:'Pin and inspect the relevant dependencies, or exclude these cases from the pilot with the reason recorded.'},
{id:'scope',title:'Technical success would not establish organisational authority',tag:'Scope limit',why:'Published decisions supply references. They do not certify the layer’s new proposals or reveal undocumented organisational intent.',next:'Keep owner acceptance, production renewal and broader organisational value separate from the technical POC verdict.'},
];

export function ProgressView(){return <>
<div className="page-heading"><span className="eyebrow">PROGRESS / 5 SEPTEMBER 2026</span><span className="reading-time">Updated {evidence.updated}</span></div>
<section className="progress-intro"><div><div className="status-line"><span className="pill green"><Check size={13}/>Evidence reviewed</span><span className="pill neutral">Pilot not started</span></div><h1>The next step is <em>one complete example.</em></h1><p className="lead">We have reviewed the candidate cases and described the experiment. We now need precise instructions for its components and a worked example that shows them operating together. That is the next preparation task; it has not been completed.</p><a href="#next-work" className="text-link">See what we will build next <ArrowRight size={16}/></a></div><aside className="credibility-card"><div className="credibility-heading"><ShieldQuestion size={21}/><span className="eyebrow">CAN WE TRUST THE EXPERIMENT?</span></div><h2>The sources are recorded.<br/>The scoring still needs validation.</h2><p>No blinded comparison has run. Before we trust a result, we must check the judges, the test tasks and the restrictions on what each agent can see.</p><a href="#credibility" className="text-link">See what has been checked <ArrowRight size={16}/></a></aside></section>
<div className="metrics"><Metric value="84" label="Examples reviewed" note="Reviewed for possible use in the experiment"/><Metric value="52" label="Candidates for the pilot" note="Some test the same underlying decision"/><Metric value="4" label="Repositories" note="All Python; three use Django"/><Metric value="0" label="Agent comparisons run" note="We have not tested whether the layer helps"/></div>
<section className="next-work" id="next-work" aria-labelledby="next-work-title">
  <span className="eyebrow">AGREED NEXT TASK / NOT COMPLETE</span>
  <h2 id="next-work-title">Write the instructions, then work through one task</h2>
  <p>We need to define exactly what each component receives, what it checks and what decision it returns:</p>
  <ul className="next-work-roles">
    <li><strong>The verifier</strong> checks whether the evidence supports the guidance drafted by the layer.</li>
    <li><strong>The checker</strong> questions the agent’s plan and actions while it works, and decides whether it can proceed.</li>
    <li><strong>The judge</strong> assesses the finished work against the reference evidence after the attempt ends.</li>
  </ul>
  <p>We will exercise those instructions on one task with a correct solution, a deliberate mistake and a valid exception. The record must show what each component saw, what it decided and why that decision was correct or incorrect.</p>
  <p className="next-work-limit">This example will help us build the procedure. We will need separate examples to validate it before trusting its scores.</p>
  <a className="text-link" href={sitePath("/evidence/working-poc-plan.md")} download>Read the recorded next step in the plan <ArrowUpRight size={16}/></a>
</section>
<section className="section-block" id="process">
  <div className="section-heading"><span className="section-no"><GitBranch size={17}/></span><div><span className="eyebrow">THE WHOLE PROCESS</span><h2>Where we are in the process</h2></div></div>
  <ol className="study-roadmap" aria-label="Study stages">
    {phases.map((p,i)=><li className={`roadmap-stage ${p.state==='Next'?'roadmap-next':''}`} key={p.id} aria-current={p.state==='Next'?'step':undefined}>
      <span className={`roadmap-number ${p.state==='Complete'?'roadmap-done':''}`} aria-hidden="true">{p.state==='Complete'?<Check size={18}/>:i+1}</span>
      <div><div className="roadmap-heading"><h3>{p.title}</h3><span className={`pill ${p.state==='Complete'?'green':p.state==='Next'?'amber':'neutral'}`}>{p.state}</span></div><p>{p.body}</p></div>
    </li>)}
  </ol>
</section>
<section className="section-block" id="credibility"><div className="section-heading"><span className="section-no">01</span><div><span className="eyebrow">CHECKS BEFORE THE TRIAL</span><h2>What we have checked</h2></div></div><div className="readiness-grid"><div className="readiness-list">{[['Fixed copies of the code and source links','Recorded','green'],['Reasons for including or excluding examples','Recorded','green'],['Checks of specific code behaviours','15 passed during preparation','blue'],['Check for answers in the allowed inputs','Not complete','amber'],['Working tasks and reliable scoring','Not validated','amber'],['Method for the main trial','Not frozen','neutral']].map(([name,state,color])=><div key={name}><span>{name}</span><span className={`pill ${color}`}>{state}</span></div>)}</div><div className="interpretation-note"><span className="eyebrow">WHAT THESE CHECKS TELL US</span><p>So far, we have checked the source material.</p><span>The 15 local checks confirmed specific code behaviours. They don’t tell us whether the layer helps an agent make better changes. We haven’t yet run a full trial in isolated containers.</span></div></div></section>
<section className="section-block" id="findings"><div className="section-heading"><span className="section-no">02</span><div><span className="eyebrow">USEFUL FINDINGS</span><h2>What we have learned so far</h2></div></div><DetailGroup>
<Disclosure id="docs" title="Sometimes the documentation and code disagree" summary="We found examples in HTTPX, NetBox and Paperless."><p>HTTPX’s guide says that setting cookies separately on each client request is unsupported. The code we inspected still accepts them, with a warning. We also found a disagreement about how HTTPX chooses the text encoding when a response does not specify one. Local checks confirmed these behaviours.</p><p>There are similar cases elsewhere. Some NetBox code uses exceptions to its general guidance for converting objects into API responses. In Paperless, the PDF-editing code we inspected schedules a new document version, which complicates the guide’s description of editing the original.</p><p><strong>Implication:</strong> we need to judge whether an answer explains the evidence correctly. Literal agreement with a single document is not a reliable test of correctness.</p><Source caseId="H11"/><Source caseId="P14"/></Disclosure>
<Disclosure id="boundaries" title="Exceptions give us more useful tests" summary="A rule may be correct in one part of the system and unnecessary in another."><p>NetBox needs to save an object’s previous state before an edit, but parts of the framework already do that. An agent has to know when extra work is needed and when it is not. We found other cases where a general setting has an exception, or where one component deliberately leaves a job to another component.</p><p><strong>Implication:</strong> a useful test should include a change that breaks the rule and an alternative that is allowed. Recognising a familiar function name would tell us much less.</p><Source caseId="N12"/><Source caseId="P13"/><Source caseId="H10"/></Disclosure>
<Disclosure id="supply" title="Several cases test the same underlying decision" summary="The 52 candidates cover 39 groups of related decisions."><p>Of the 84 examples reviewed, 52 are candidates for further development. Fifteen are intended to check whether the layer admits that a rule cannot be established from the evidence. Six need more investigation, four are simple checks to help us test the scoring, three overlap with another case, and four were rejected. Six of the 52 candidates had already been used in our initial development work.</p><p><strong>Implication:</strong> we have material to build the pilot, but the number of rows does not establish that the main trial will be large enough. We need to allow for related cases and choose its size based on the improvement we want to detect.</p><a className="text-link" href={sitePath("/evidence/cross-repository-inventory-review.md")} download>Read the inventory assessment <ArrowUpRight size={16}/></a></Disclosure>
</DetailGroup></section>
<section className="section-block" id="risks"><div className="section-heading"><span className="section-no">03</span><div><span className="eyebrow">RISKS & ISSUES</span><h2>Issues we still need to resolve</h2></div></div><DetailGroup>{risks.map(r=><Disclosure key={r.id} id={r.id} title={r.title} summary={r.tag}><div className="detail-columns"><div><h3>Why it matters</h3><p>{r.why}</p></div><div><h3>What we need to do</h3><p>{r.next}</p></div></div></Disclosure>)}</DetailGroup></section>
<section className="section-block"><div className="section-heading"><span className="section-no">04</span><div><span className="eyebrow">DECISIONS STILL TO MAKE</span><h2>Before we run the pilot</h2></div></div><p className="section-intro">We’ll discuss these choices in the working conversation and record the decisions here as we go.</p><div className="decision-list">{[
['01','What exactly should each component do in the first development case?','The agreed next step is to write precise instructions for the verifier, checker and judge, then exercise them on one complete case. Its evidence must justify the expected decisions. This case will help build the system; it will not count as independent validation.'],
['02','Which decisions should the first trial cover?','Choose cases from several repositories, including rules the code supports, legitimate exceptions, disagreements with documentation and questions the code cannot answer.'],
['03','Does the proposed checking procedure work for the pilot cases?','Start with a plan check before editing and checks on submitted code changes. Require a new plan for a changed approach, and allow at most two correction rounds per checkpoint. Build and validate this proposal before treating it as the trial procedure.'],
['04','How do we make the three conditions comparable?','Compare direct work from the sources, prepared guidance alone, and the same guidance with interaction. Give them comparable resources and count the cost of preparing guidance and checking the work.'],
['05','How much improvement would justify the extra work?','Agree what reduction in mistakes would be worthwhile and how much additional cost or unnecessary intervention is acceptable. Use those choices to plan the main trial.']
].map(([n,title,body])=><div key={n}><span className="section-no">{n}</span><div><h3>{title}</h3><p>{body}</p></div><span className="pill neutral">Open</span></div>)}</div><DetailGroup><Disclosure id="direction" title="What we currently propose" summary="The main trial’s method and success criteria have not yet been agreed."><ul className="plain-list"><li>Use NetBox, Wagtail, Paperless-ngx and HTTPX as sources of candidate cases.</li><li>Check interpretations against explicit project records, while keeping owner approval outside this technical test.</li><li>Build a small pilot to check the tasks, information restrictions and scoring before committing to a larger trial.</li><li>Distinguish the value of preparing guidance from the additional value of consulting the layer and checking the agent’s use of it.</li></ul></Disclosure></DetailGroup></section>
<section className="section-block" id="evidence"><div className="section-heading"><span className="section-no">05</span><div><span className="eyebrow">EVIDENCE RECORD</span><h2>Sources and research record</h2></div></div><DetailGroup><Disclosure id="repos" title="Repository coverage" summary="The four pinned snapshots and their roles in the study."><RepositoryCards showCounts/></Disclosure><Disclosure id="inventory" title="Browse all 84 candidate records" summary="Search by decision, repository or screening disposition."><EvidenceExplorer/></Disclosure><Disclosure id="reports" title="Reports and supporting records" summary="Download the assessment, case cards and screening protocol."><EvidenceDownloads/></Disclosure><Disclosure id="history" title="Research activity" summary="Latest evidence work completed on 5 September 2026."><div className="activity-list">{[['Broader inventory completed','84 records screened across four repositories. Fifteen new local development checks passed.'],['NetBox feasibility audit completed','Twelve initial cases distinguished recoverable conventions, conflicts, conditional guidance and policies requiring authority.'],['Original POC design reviewed','The review identified reference-independence, baseline, scoring and scope issues requiring a redesigned evaluation.']].map(([title,body])=><div key={title}><Clock3 size={17}/><div><span className="eyebrow">05 SEP 2026</span><h3>{title}</h3><p>{body}</p></div></div>)}</div></Disclosure></DetailGroup></section>
<div className="route-footer"><span>Read why we are running the study and how it will work.</span><PageLink href="/">The experiment <ArrowRight size={18}/></PageLink></div>
</>}
function Metric({value,label,note}:{value:string,label:string,note:string}){return <div className="metric"><span className="metric-value">{value}</span><strong>{label}</strong><p>{note}</p></div>}
function Source({caseId}:{caseId:string}){const c=evidence.cases.find(c=>c.id===caseId)!;return <a href={c.reference.url} target="_blank" rel="noreferrer" className="finding-source">{caseId} · {c.title}<ArrowUpRight size={14}/></a>}
