#!/usr/bin/env python3
"""Plan v1.2 item F4: hidden-test name coupling per selected ticket.

For each selected ticket, diff the fixing PR (first parent -> merge commit) and list
the top-level classes and functions the PR *introduced* in non-test source that its
tests reference by name. A fix that names its new class differently fails those tests
at import time regardless of correctness. Mechanical; no judgment.

Also records: test files in the PR, whether the PR ships a migration, and the import
lines the tests added. The column "issue text names the interface" is filled by a
separate step that needs the issue body (data/issues/<n>.json); it is left "pending"
when the body is not present.

Outputs: data/name_coupling.json, data/name_coupling.md
Requires: full netbox clone at FG_UPSTREAM (default /tmp/netbox-up).
"""
import json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPSTREAM = os.environ.get("FG_UPSTREAM", "/tmp/netbox-up")
GENERIC = {"save", "get", "post", "filter", "delete", "clean", "__init__", "__str__", "run", "setUp",
           "setUpTestData", "get_queryset", "to_representation", "validate", "collect", "retrieve", "deconstruct"}

def sh(args):
    return subprocess.run(args, cwd=UPSTREAM, capture_output=True, text=True, check=True).stdout

def main():
    rows = []
    for line in open(os.path.join(ROOT, "preregistration", "selected_tickets.md"), encoding="utf-8-sig"):
        m = re.match(r"\|\s*(\d+)\s*\|\s*#(\d+)\s*\|\s*(\d+)\s*\|.*?\|\s*([0-9a-f]{40})\s*\|", line)
        if not m:
            continue
        seq, issue, pr, merge = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
        files = [f for f in sh(["git", "diff", "--name-only", merge + "^", merge]).split() if f]
        tests = [f for f in files if "/tests/" in f]
        src = [f for f in files if f.endswith(".py") and "/tests/" not in f and "/migrations/" not in f]
        migrations = [f for f in files if "/migrations/" in f and f.endswith(".py")]
        new_syms = set()
        for f in src:
            for l in sh(["git", "diff", merge + "^", merge, "--", f]).splitlines():
                mm = re.match(r"\+\s*(?:class|def|async def)\s+([A-Za-z_]\w*)", l)
                if mm and mm.group(1) not in GENERIC:
                    new_syms.add(mm.group(1))
        test_text = "".join(sh(["git", "show", f"{merge}:{f}"]) for f in tests)
        coupled = sorted(s for s in new_syms if re.search(r"\b" + re.escape(s) + r"\b", test_text))
        added_imports = sorted({l[1:].strip() for f in tests for l in sh(["git", "diff", merge + "^", merge, "--", f]).splitlines()
                                if re.match(r"\+\s*(from|import)\s", l)})
        issue_path = os.path.join(ROOT, "data", "issues", f"{issue}.json")
        names_iface = "pending"
        if os.path.exists(issue_path):
            body = (json.load(open(issue_path)).get("body") or "") + " " + json.load(open(issue_path)).get("title", "")
            hits = [s for s in coupled if re.search(r"\b" + re.escape(s) + r"\b", body)]
            names_iface = ("yes: " + ", ".join(hits)) if hits else "no"
        rows.append(dict(seq=seq, issue=issue, pr=pr, merge=merge, test_files=tests, migration_files=migrations,
                         new_symbols_in_source=sorted(new_syms), coupled_symbols=coupled,
                         coupled=bool(coupled), test_added_imports=added_imports, issue_names_interface=names_iface))
        print(f"#{issue}: coupled={bool(coupled)} {coupled}")
    json.dump(rows, open(os.path.join(ROOT, "data", "name_coupling.json"), "w"), indent=1)
    n = sum(r["coupled"] for r in rows)
    md = ["# Hidden-test name coupling (plan v1.2, F4)", "",
          "Mechanical check per selected ticket: which top-level classes or functions the reference fix introduced in "
          "non-test source are referenced by name in its tests. Generic method names (save, get, filter, ...) are ignored. "
          "A correct fix that names these differently fails at import time; such failures are class (ii) in the pass "
          "taxonomy and are reported per arm, never excluded by default. Generated by `scripts/name_coupling.py`.", "",
          f"Result: {n} of {len(rows)} tickets are coupled to at least one reference-invented name.", "",
          "| # | Issue | PR | Coupled | Reference-invented names used by the tests | PR ships migration | Issue text names the interface |",
          "|---|---|---|---|---|---|---|"]
    for r in rows:
        md.append(f"| {r['seq']} | #{r['issue']} | {r['pr']} | {'yes' if r['coupled'] else 'no'} | "
                  f"{', '.join('`'+s+'`' for s in r['coupled_symbols']) or '-'} | {'yes' if r['migration_files'] else 'no'} | {r['issue_names_interface']} |")
    open(os.path.join(ROOT, "data", "name_coupling.md"), "w").write("\n".join(md) + "\n")

if __name__ == "__main__":
    main()
